filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: secret-infra
repositories:
- name: external-secrets
  url: https://external-secrets.github.io/kubernetes-external-secrets
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: wave-k8s
  url: https://wave-k8s.github.io/wave/
- name: bank-vaults
  url: ghcr.io/bank-vaults/helm-charts
  oci: true
releases:
- chart: external-secrets/kubernetes-external-secrets
  version: 8.5.5
  name: kubernetes-external-secrets
  values:
  - ../../versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  - jx-values.yaml
- chart: bank-vaults/vault-operator
  version: 1.22.3
  name: vault-operator
  values:
  - jx-values.yaml
- chart: jxgh/vault-instance
  version: 1.0.28
  name: vault-instance
  values:
  - jx-values.yaml
- chart: wave-k8s/wave
  version: 4.2.0
  name: wave
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
